package com.uciap.medicrea.report;

import com.uciap.medicrea.model.LabResult;
import com.uciap.medicrea.model.Patient;
import com.uciap.medicrea.model.Prescription;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

@Component
public class ReportGenerator {

    private static final String TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Medical Report</title>

<style>
  body {
    background: #eaeaea;
    font-family: "Segoe UI", Arial, sans-serif;
  }

  .report {
    width: 210mm;
    min-height: 297mm;
    margin: 20px auto;
    padding: 20mm;
    background: #ffffff;
    color: #000;
    box-shadow: 0 0 12px rgba(0,0,0,0.15);
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .header h1 {
    margin: 0;
    font-size: 22px;
  }

  .logo {
    width: 120px;
    height: 80px;
    border: 1px solid #000;
    font-size: 11px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  hr {
    margin: 15px 0;
    border-top: 2px solid #000;
  }

  .meta {
    display: flex;
    justify-content: space-between;
    font-size: 14px;
    margin-bottom: 20px;
  }

  h2 {
    font-size: 18px;
    margin-top: 25px;
    border-bottom: 2px solid #000;
    padding-bottom: 5px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 10px;
  }

  th, td {
    border: 1px solid #000;
    padding: 8px;
    font-size: 14px;
    vertical-align: top;
  }

  th {
    background: #f4f4f4;
    text-align: left;
  }

  ul {
    margin-top: 10px;
    font-size: 14px;
  }

  .history-item {
    margin-bottom: 12px;
    padding-bottom: 8px;
    border-bottom: 1px dashed #999;
  }

  .footer {
    display: flex;
    justify-content: space-between;
    margin-top: 50px;
    font-size: 14px;
  }

  .disclaimer {
    margin-top: 20px;
    font-size: 12px;
    color: #555;
  }

  @media print {
    body { background: none; }
    .report { margin: 0; box-shadow: none; }
  }
</style>
</head>

<body>
<div class="report">

<div class="header">
  <div>
    <h1>{{HOSPITAL_NAME}}</h1>
    <p>{{HOSPITAL_ADDRESS}}</p>
    <p>{{HOSPITAL_CONTACT}}</p>
  </div>
  <div class="logo">LOGO</div>
</div>

<hr>

<div class="meta">
  <div>
    <strong>Report ID:</strong> {{REPORT_ID}}<br>
    <strong>Generated At:</strong> {{GENERATED_AT}}
  </div>
  <div>
    <strong>Generated By:</strong> Hospital System
  </div>
</div>

<h2>Patient Information</h2>
<table>
  <tr>
    <th>Name</th><td>{{PATIENT_NAME}}</td>
    <th>Age</th><td>{{PATIENT_AGE}}</td>
  </tr>
  <tr>
    <th>Gender</th><td>{{GENDER}}</td>
    <th>NIC</th><td>{{NIC}}</td>
  </tr>
  <tr>
    <th>Contact</th><td colspan="3">{{CONTACT}}</td>
  </tr>
</table>

<h2>Medical History (Latest First)</h2>
{{MEDICAL_HISTORY_BLOCKS}}

<h2>Laboratory Results</h2>
<table>
<tr>
  <th>Date</th>
  <th>Test</th>
  <th>Result</th>
  <th>Normal Range</th>
</tr>
{{LAB_RESULTS_ROWS}}
</table>

<h2>Prescription History</h2>
<ul>
{{PRESCRIPTION_ITEMS}}
</ul>

<div class="footer">
  <div>
    <p>__________________________</p>
    <p>Authorized Medical Officer</p>
  </div>
  <div>
    <p>Date: {{GENERATED_DATE}}</p>
  </div>
</div>

<div class="disclaimer">
This medical report is system-generated.<br>
Any modification invalidates its authenticity.<br>
Report Hash (SHA-256): {{REPORT_HASH}}
</div>

</div>
</body>
</html>
""";

    private static final String HOSPITAL_NAME = "SmartCare General Hospital";
    private static final String HOSPITAL_ADDRESS = "123 Wellness Avenue, Springfield";
    private static final String HOSPITAL_CONTACT = "+94 11 200 3000";
    private static final DateTimeFormatter DATE_TIME =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public String generateReport(
            Patient patient,
            List<Prescription> prescriptions,
            List<LabResult> labResults,
            Map<String, String> doctorNames,
            Map<String, String> labNormalRanges,
            String reportId,
            LocalDateTime generatedAt,
            String reportHash
    ) {

        if (patient == null) {
            throw new IllegalArgumentException("Patient must not be null");
        }

        String html = TEMPLATE;
        html = html.replace("{{HOSPITAL_NAME}}", HOSPITAL_NAME);
        html = html.replace("{{HOSPITAL_ADDRESS}}", HOSPITAL_ADDRESS);
        html = html.replace("{{HOSPITAL_CONTACT}}", HOSPITAL_CONTACT);
        html = html.replace("{{REPORT_ID}}", safe(reportId));
        html = html.replace("{{GENERATED_AT}}", DATE_TIME.format(generatedAt));
        html = html.replace("{{GENERATED_DATE}}", DATE_TIME.format(generatedAt));

        html = html.replace("{{PATIENT_NAME}}", safe(patient.getFullName()));
        html = html.replace("{{PATIENT_AGE}}", resolveAge(patient));
        html = html.replace("{{GENDER}}", safe(patient.getGender()));
        html = html.replace("{{NIC}}", safe(patient.getNic()));
        html = html.replace("{{CONTACT}}", safe(patient.getContact()));

        html = html.replace(
                "{{MEDICAL_HISTORY_BLOCKS}}",
                buildMedicalHistory(prescriptions, doctorNames)
        );

        html = html.replace(
                "{{LAB_RESULTS_ROWS}}",
                buildLabRows(labResults, labNormalRanges)
        );

        html = html.replace(
                "{{PRESCRIPTION_ITEMS}}",
                buildPrescriptionItems(prescriptions, doctorNames)
        );

        html = html.replace("{{REPORT_HASH}}", safe(reportHash));

        return html;
    }

    private String buildMedicalHistory(
            List<Prescription> prescriptions,
            Map<String, String> doctorNames
    ) {
        if (prescriptions == null || prescriptions.isEmpty()) {
            return "<div class=\"history-item\"><strong>No history available.</strong></div>";
        }

        return prescriptions.stream()
                .sorted(Comparator.comparing(
                        Prescription::getIssuedDate,
                        Comparator.nullsLast(Comparator.reverseOrder())
                ))
                .map(p -> """
<div class="history-item">
<strong>Date:</strong> %s<br>
<strong>Doctor:</strong> %s<br>
<strong>Prescription:</strong> %s (%s) – %s
</div>
""".formatted(
                        formatDate(p.getIssuedDate()),
                        resolveDoctorName(p.getDoctorId(), doctorNames),
                        safe(p.getMedicineName()),
                        safe(p.getDosage()),
                        safe(p.getFrequency())
                ))
                .collect(Collectors.joining());
    }

    private String buildLabRows(
            List<LabResult> labResults,
            Map<String, String> labNormalRanges
    ) {
        if (labResults == null || labResults.isEmpty()) {
            return "<tr><td colspan=\"4\">No lab results available</td></tr>";
        }

        return labResults.stream()
                .sorted(Comparator.comparing(
                        LabResult::getResultDate,
                        Comparator.nullsLast(Comparator.reverseOrder())
                ))
                .map(r -> """
<tr>
<td>%s</td>
<td>%s</td>
<td>%s</td>
<td>%s</td>
</tr>
""".formatted(
                        formatDate(r.getResultDate()),
                        safe(r.getTestName()),
                        safe(r.getResult()),
                        safe(labNormalRanges.getOrDefault(
                                r.getTestName().toLowerCase(), "N/A"
                        ))
                ))
                .collect(Collectors.joining());
    }

    private String buildPrescriptionItems(
            List<Prescription> prescriptions,
            Map<String, String> doctorNames
    ) {
        if (prescriptions == null || prescriptions.isEmpty()) {
            return "<li>No prescriptions recorded.</li>";
        }

        return prescriptions.stream()
                .sorted(Comparator.comparing(
                        Prescription::getIssuedDate,
                        Comparator.nullsLast(Comparator.reverseOrder())
                ))
                .map(p -> "<li>" +
                        safe(p.getMedicineName()) + " " +
                        safe(p.getDosage()) + " – " +
                        safe(p.getFrequency()) + " (" +
                        formatDate(p.getIssuedDate()) + ") by " +
                        resolveDoctorName(p.getDoctorId(), doctorNames) +
                        "</li>")
                .collect(Collectors.joining());
    }

    private String resolveDoctorName(String doctorId, Map<String, String> doctorNames) {
        return doctorId == null
                ? "Unknown Doctor"
                : safe(doctorNames.getOrDefault(doctorId, "Unknown Doctor"));
    }

    private String resolveAge(Patient patient) {
        LocalDate dob = patient.getDateOfBirth();
        if (dob == null) return "N/A";
        int years = Period.between(dob, LocalDate.now()).getYears();
        return years >= 0 ? String.valueOf(years) : "N/A";
    }

    private String formatDate(LocalDate date) {
        return date != null ? date.toString() : "N/A";
    }

    private String safe(String value) {
        if (value == null || value.isBlank()) return "N/A";
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
